---
name: Build Distributions

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  build:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"  # yamllint disable-line rule:quoted-strings

      - name: Check Python source
        run: uv run ruff check && uv run ruff format --diff

      - name: Build Python distributions
        run: uv build --no-cache
