---
name: Check Source Code

on:  # yamllint disable-line rule:truthy
  pull_request:  # yamllint disable-line rule:empty-values
  push:
    branches:
      - main

jobs:
  check:
    name: Check Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up yamllint
        run: uv tool install yamllint

      - name: Run yamllint
        run: uv tool run yamllint .

      - name: Check Python source
        run: uv run ruff check && uv run ruff format --diff
